/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as ImportIndexRouteImport } from './routes/import.index'
import { Route as SubjectsSubjectIdIndexRouteImport } from './routes/subjects.$subjectId.index'
import { Route as ImportNoteIdIndexRouteImport } from './routes/import.$noteId.index'
import { Route as SubjectsSubjectIdDecksDeckIdRouteImport } from './routes/subjects.$subjectId.decks.$deckId'
import { Route as ImportNoteIdGenerationsGenerationIdRouteImport } from './routes/import.$noteId.generations.$generationId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportIndexRoute = ImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdIndexRoute = SubjectsSubjectIdIndexRouteImport.update({
  id: '/subjects/$subjectId/',
  path: '/subjects/$subjectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportNoteIdIndexRoute = ImportNoteIdIndexRouteImport.update({
  id: '/import/$noteId/',
  path: '/import/$noteId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdDecksDeckIdRoute =
  SubjectsSubjectIdDecksDeckIdRouteImport.update({
    id: '/subjects/$subjectId/decks/$deckId',
    path: '/subjects/$subjectId/decks/$deckId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImportNoteIdGenerationsGenerationIdRoute =
  ImportNoteIdGenerationsGenerationIdRouteImport.update({
    id: '/import/$noteId/generations/$generationId',
    path: '/import/$noteId/generations/$generationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/planning': typeof PlanningRoute
  '/review': typeof ReviewRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/import/': typeof ImportIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/import/$noteId/': typeof ImportNoteIdIndexRoute
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
  '/import/$noteId/generations/$generationId': typeof ImportNoteIdGenerationsGenerationIdRoute
  '/subjects/$subjectId/decks/$deckId': typeof SubjectsSubjectIdDecksDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/planning': typeof PlanningRoute
  '/review': typeof ReviewRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/import': typeof ImportIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/import/$noteId': typeof ImportNoteIdIndexRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdIndexRoute
  '/import/$noteId/generations/$generationId': typeof ImportNoteIdGenerationsGenerationIdRoute
  '/subjects/$subjectId/decks/$deckId': typeof SubjectsSubjectIdDecksDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/planning': typeof PlanningRoute
  '/review': typeof ReviewRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/import/': typeof ImportIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/import/$noteId/': typeof ImportNoteIdIndexRoute
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
  '/import/$noteId/generations/$generationId': typeof ImportNoteIdGenerationsGenerationIdRoute
  '/subjects/$subjectId/decks/$deckId': typeof SubjectsSubjectIdDecksDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/login'
    | '/planning'
    | '/review'
    | '/set-password'
    | '/settings'
    | '/import/'
    | '/subjects/'
    | '/import/$noteId/'
    | '/subjects/$subjectId/'
    | '/import/$noteId/generations/$generationId'
    | '/subjects/$subjectId/decks/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/login'
    | '/planning'
    | '/review'
    | '/set-password'
    | '/settings'
    | '/import'
    | '/subjects'
    | '/import/$noteId'
    | '/subjects/$subjectId'
    | '/import/$noteId/generations/$generationId'
    | '/subjects/$subjectId/decks/$deckId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/login'
    | '/planning'
    | '/review'
    | '/set-password'
    | '/settings'
    | '/import/'
    | '/subjects/'
    | '/import/$noteId/'
    | '/subjects/$subjectId/'
    | '/import/$noteId/generations/$generationId'
    | '/subjects/$subjectId/decks/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LoginRoute: typeof LoginRoute
  PlanningRoute: typeof PlanningRoute
  ReviewRoute: typeof ReviewRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  ImportIndexRoute: typeof ImportIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  ImportNoteIdIndexRoute: typeof ImportNoteIdIndexRoute
  SubjectsSubjectIdIndexRoute: typeof SubjectsSubjectIdIndexRoute
  ImportNoteIdGenerationsGenerationIdRoute: typeof ImportNoteIdGenerationsGenerationIdRoute
  SubjectsSubjectIdDecksDeckIdRoute: typeof SubjectsSubjectIdDecksDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/': {
      id: '/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof ImportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId/': {
      id: '/subjects/$subjectId/'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId/'
      preLoaderRoute: typeof SubjectsSubjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/$noteId/': {
      id: '/import/$noteId/'
      path: '/import/$noteId'
      fullPath: '/import/$noteId/'
      preLoaderRoute: typeof ImportNoteIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId/decks/$deckId': {
      id: '/subjects/$subjectId/decks/$deckId'
      path: '/subjects/$subjectId/decks/$deckId'
      fullPath: '/subjects/$subjectId/decks/$deckId'
      preLoaderRoute: typeof SubjectsSubjectIdDecksDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/$noteId/generations/$generationId': {
      id: '/import/$noteId/generations/$generationId'
      path: '/import/$noteId/generations/$generationId'
      fullPath: '/import/$noteId/generations/$generationId'
      preLoaderRoute: typeof ImportNoteIdGenerationsGenerationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LoginRoute: LoginRoute,
  PlanningRoute: PlanningRoute,
  ReviewRoute: ReviewRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRoute,
  ImportIndexRoute: ImportIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  ImportNoteIdIndexRoute: ImportNoteIdIndexRoute,
  SubjectsSubjectIdIndexRoute: SubjectsSubjectIdIndexRoute,
  ImportNoteIdGenerationsGenerationIdRoute:
    ImportNoteIdGenerationsGenerationIdRoute,
  SubjectsSubjectIdDecksDeckIdRoute: SubjectsSubjectIdDecksDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
